# frozen_string_literal: true

require 'yaml'

# Import screen and lookup YAML translations.
# Reads YAML files generated by ConfigTranslationExporter and applies
# locale-specific values to Screen and Lookup records.
class ConfigTranslationImporter
  attr_accessor :file_name, :locale, :errors

  def initialize(opts = {})
    @file_name = opts[:file_name]
    @errors = []
  end

  def import
    return log_error('Import Not Processed: No file_name passed in') if file_name.blank?

    config_data = YAML.load_file(file_name)
    return log_error("Import Not Processed: error reading #{file_name}") if config_data.blank?
    return log_error('Import Not Processed: invalid yml format') unless config_data.is_a?(Hash)

    process_import_file(config_data)
  end

  private

  def process_import_file(config_data)
    @locale = valid_locale(config_data)
    return if @locale.blank?

    payload = config_data.values.first
    import_screens(payload['screens']) if payload.key?('screens')
    import_lookups(payload['lookups']) if payload.key?('lookups')
  end

  def valid_locale(config_data)
    locale = config_data.keys.first&.to_sym
    return log_error('Import Not Processed: locale not passed in') if locale.blank?
    if I18n.available_locales.exclude?(locale)
      return log_error("Import Not Processed: locale #{locale} not in available locales")
    end

    locale.to_s
  end

  def import_screens(screens_hash)
    screens_hash.each do |screen_id, translations|
      screen = Screen.find_by("data ->> 'id' = ?", screen_id)
      next log_info("Screen [#{screen_id}] not found. Skipping.") unless screen

      log_info("Updating Screen [#{screen_id}] for locale [#{@locale}]")

      screen.update_translations(@locale, translations)
      log_info("Updated Screen [#{screen_id}] for locale [#{@locale}]")
    end
  end

  def import_lookups(lookups_hash)
    lookups_hash.each do |lookup_name, options_hash|
      lookup = Lookup.find_by(name: lookup_name)
      next log_info("Lookup [#{lookup_name}] not found. Skipping.") unless lookup

      lookup.update_translations(@locale, options_hash)
      log_info("Updated Lookup [#{lookup_name}] for locale [#{@locale}]")
    end
  end

  def log_error(message)
    Rails.logger.error(message)
    @errors << message
    nil
  end

  def log_info(message)
    Rails.logger.info(message)
    p message
  end
end
