export const Strings = {
    app: "app",
    buttonsBack: "buttons.back",
    buttonsContinue: "buttons.continue",
    buttonsSkip: "buttons.skip",
    character: "character.name",
    characterIcon: "character.icon",
    characterInformation: "CharacterInformation",
    characterSelection: "CharacterSelection",
    characterWelcome: "CharacterWelcome",
    comfortingResponse: "ComfortingResponse",
    empty: "",
    featuredImage: "Featured Image",
    featuredImageAlt: "Featured Image",
    form: "form",
    hub: "Hub",
    hubWithCharacter: "HubWithCharacter",
    idb: "idb",
    input_1: "input_1",
    input_2: "input_2",
    json: "json",
    kioskName: "kiosk_name",
    language: "language",
    languageSelect: "LanguageSelect",
    locales: "locales",
    localStorage: "localStorage",
    logo: "logo",
    lookup: "lookup",
    lookups: "lookups",
    ltr: "ltr",
    multiSelect: "MultiSelect",
    notImplemented: "Not Implemented",
    onResolved: "onResolved",
    outline: "outline",
    placeholder: "placeholder",
    radio: "radio",
    records: "records",
    responseGoodBye: "ResponseGoodBye",
    rtl: "rtl",
    rtlLocales: "rtl_locales",
    scope: "scope",
    screenNotFound: "Screen Not Found",
    screens: "screens",
    secondary: "secondary",
    selectWithTextArea: "SelectWithTextArea",
    settings: "settings",
    singleSelect: "SingleSelect",
    span: "span",
    startingScreenID: "starting_screen_id",
    string: "string",
    submit: "submit",
    svgError: "Error loading svg image",
    svgExtenstion: ".svg",
    svgType: "image/svg+xml",
    systemSettings: "systemSettings",
    textArea: "TextArea",
    theme: "theme",
} as const;

export const RouteStrings = {
    root: "/",
    screensByID: "/screens/$id",
};

export const BASE_URL = "/api";

export const ENDPOINTS = {
    lookups: "/lookups",
    screens: "/screens",
    systemSettings: "/system_settings",
    theme: "/theme",
} as const;
