export const Strings = {
    app: "app",
    appFlow: "appFlow",
    buttonsBack: "buttons.back",
    buttonsContinue: "buttons.continue",
    buttonsSkip: "buttons.skip",
    captcha: "captcha",
    captchaResponse: "captchaResponse",
    character: "character.name",
    characterIcon: "character.icon",
    characterInformation: "CharacterInformation",
    characterPurpose: "CharacterPurpose",
    characterSelection: "CharacterSelection",
    characterWelcome: "CharacterWelcome",
    comfortingResponse: "ComfortingResponse",
    empty: "",
    featuredImage: "Featured Image",
    featuredImageAlt: "Featured Image",
    flow: "flow",
    form: "form",
    global: "global",
    hub: "Hub",
    hubWelcome: "HubWelcome",
    hubWithCharacter: "HubWithCharacter",
    idb: "idb",
    input_1: "input_1",
    input_2: "input_2",
    json: "json",
    kioskLanguage: "kiosk.language",
    kioskName: "kiosk_name",
    language: "language",
    languageSelect: "LanguageSelect",
    locales: "locales",
    localStorage: "localStorage",
    logo: "logo",
    logoPictorial: "logo_pictorial",
    logoPictorialSecondary: "logo_pictorial_secondary",
    lookup: "lookup",
    lookupID: "lookup_id",
    lookups: "lookups",
    ltr: "ltr",
    multiSelect: "MultiSelect",
    multiSelectOrWrite: "MultiSelectOrWrite",
    notImplemented: "Not Implemented",
    onResolved: "onResolved",
    outline: "outline",
    placeholder: "placeholder",
    radio: "radio",
    recordRiskLevel: "records.risk_level",
    records: "records",
    responseGoodBye: "ResponseGoodBye",
    retryRecord: "retryRecord",
    retrySuccessNextScreen: "retrySuccessNextScreen",
    rtl: "rtl",
    rtlLocales: "rtl_locales",
    scope: "scope",
    screenNotFound: "Screen Not Found",
    screens: "screens",
    secondary: "secondary",
    selectOrWrite: "SelectOrWrite",
    selectWithTextArea: "SelectWithTextArea",
    sessionStorage: "sessionStorage",
    settings: "settings",
    singleSelect: "SingleSelect",
    span: "span",
    startingScreenID: "starting_screen_id",
    string: "string",
    submit: "submit",
    svgError: "Error loading svg image",
    svgExtenstion: ".svg",
    svgType: "image/svg+xml",
    systemSettings: "systemSettings",
    textArea: "TextArea",
    textInput: "TextInput",
    theme: "theme",
    type: "type",
} as const;

export const RISK_LEVELS: Record<string, number> = {
    high: 3,
    low: 1,
    medium: 2,
} as const;

export const RouteStrings = {
    root: "/",
    screensByID: "/$flow/$id",
};

export const BASE_URL = "/api";

export const ENDPOINTS = {
    appFlows: "/app_flows",
    lookups: "/lookups",
    records: "/records",
    systemSettings: "/system_settings",
    theme: "/theme",
} as const;
