# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Test
    displayName: 'Run Tests'
    pool: $(buildAgentPool)
    steps:
      - bash: echo "Installing dependencies"

  - job: Build
    displayName: 'Build and push to ACR'
    dependsOn: Test
    pool: $(buildAgentPool)
    steps:
      - checkout: self
        fetchDepth: 0

      - bash: |
          set -euo pipefail

          SHORT_COMMIT_ID="$(echo "$(Build.SourceVersion)" | tail -c 10)"
          if [ -n "$(Build.SourceBranchName)" ] && [[ "$(Build.SourceBranch)" == refs/tags/* ]]; then
            RAW_TAG="$(Build.SourceBranchName)"
          else
            RAW_TAG="$(Build.SourceBranchName)-$SHORT_COMMIT_ID"
          fi

          # Docker-safe tag
          IMAGE_TAG=$(echo "$RAW_TAG" \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's#[^a-z0-9._-]#-#g')

          echo "Using image tag: $IMAGE_TAG"
          echo "##vso[task.setvariable variable=IMAGE_TAG]$IMAGE_TAG"
        displayName: 'Generate Image Tag'

      - task: AzureCLI@2
        displayName: 'Build and Push to ACR'
        inputs:
          azureSubscription: $(AZURE_SERVICE_CONNECTION)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            set -euo pipefail

            az acr login --name "$(acrName)"

            IMAGE_NAME="$(acrName)/primero-kiosk/application"
            echo "Building Docker image: $IMAGE_NAME"

            docker build \
              --build-arg APP_ROOT=/srv/kiosk \
              --build-arg APP_UID=1000 \
              --build-arg APP_GID=1000 \
              -t "${IMAGE_NAME}:$(IMAGE_TAG)" \
              -f "./docker/application/Dockerfile" \
              ./

            if [[ "$(Build.SourceBranchName)" == "main" ]]; then
                docker tag "${IMAGE_NAME}:$(IMAGE_TAG)" "${IMAGE_NAME}:latest"
            fi

            docker image ls ${IMAGE_NAME}

            docker push "${IMAGE_NAME}:$(IMAGE_TAG)"

            if [[ "$(Build.SourceBranchName)" == "main" ]]; then
                docker push "${IMAGE_NAME}:latest"
                docker rmi "${IMAGE_NAME}:latest"
            fi

            # Cleanup image to free up space
            docker rmi "${IMAGE_NAME}:$(IMAGE_TAG)"

