default: &default
  adapter: postgresql
  database: <%= ENV["POSTGRES_DATABASE"] %>
  username: <%= ENV["POSTGRES_USER"] || 'primero' %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOSTNAME"] %>
  sslmode: <%= ENV["POSTGRES_SSL_MODE"] %>
  pool: <%= ENV["POSTGRES_POOL_NUM"] || 5 %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
