development:
  default_locale: <%= ENV['LOCALE_DEFAULT'] || 'en' %>
  locales: <%= ENV['LOCALE_ALL']&.split(',') %>

test:
  default_locale: <%= ENV['LOCALE_DEFAULT'] || 'en' %>
  locales: <%= ENV['LOCALE_ALL']&.split(',') %>

production:
  default_locale: <%= ENV['LOCALE_DEFAULT'] || 'en' %>
  locales: <%= ENV['LOCALE_ALL']&.split(',') %>
